# Generated by Django 5.2.8 on 2025-11-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='other', max_length=10, null=True)),
                ('other_pet_type', models.CharField(blank=True, help_text="Specify if pet_type is 'Other' (e.g., Rabbit, Bird)", max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('health', models.TextField(blank=True)),
                ('favorite_food', models.CharField(blank=True, max_length=100)),
                ('favorite_toy', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('inactive', 'Inactive')], default='available', max_length=10)),
                ('likes', models.CharField(blank=True, max_length=100)),
                ('hates', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['name'],
            },
        ),
    ]
